apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  containers:
  - args:
    - /run.sh
    resources:
      requests:
        cpu: 0.1
        memory: 100M
      limits:
        cpu: 0.5
        memory: 300M
    image: anderssv/openshift-cassandra:latest
    name: cassandra
    ports:
    - name: cql
      containerPort: 9042
    - name: thrift
      containerPort: 9160
    volumeMounts:
    - name: data
      mountPath: /cassandra_data
    env:
    - name: MAX_HEAP_SIZE
      value: 256M
    - name: HEAP_NEWSIZE
      value: 64M
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  volumes:
    - name: data
      emptyDir: {}
