apiVersion: v1
kind: List
metadata: {}
items:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: cassandra-pvc-1
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 500M


- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      app: cassandra
    name: cassandra
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cassandra
      spec:
        containers:
          - command:
              - /run.sh
            resources:
              requests:
                cpu: 0.1
                memory: 100M
              limits:
                cpu: 0.5
                memory: 300M
            env:
              - name: MAX_HEAP_SIZE
                value: 512M
              - name: HEAP_NEWSIZE
                value: 100M
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
            image: anderssv/openshift-cassandra:latest
            name: cassandra
            ports:
              - containerPort: 9042
                name: cql
              - containerPort: 9160
                name: thrift
            volumeMounts:
              - mountPath: /cassandra_data
                name: cassandra-data
        volumes:
        - name: cassandra-data
          persistentVolumeClaim:
            claimName: cassandra-pvc-1
